"""Authentication primitives for provider integrations."""

from .credentials import (
    ConnectionStatus,
    CredentialBackend,
    CredentialDisconnectedError,
    CredentialError,
    CredentialRef,
    CredentialReference,
    CredentialStore,
    InMemoryCredentialBackend,
    KeyringCredentialBackend,
    MemoryCredentialBackend,
    PermanentRefreshError,
    ProviderAccount,
    ProviderAuthHandler,
    RefreshCallback,
    RevocationCallback,
    TokenSet,
    new_credential_reference,
    redact_headers,
    redact_mapping,
    redact_secret,
    redact_text,
)

__all__ = [
    "ConnectionStatus",
    "CredentialBackend",
    "CredentialDisconnectedError",
    "CredentialError",
    "CredentialRef",
    "CredentialReference",
    "CredentialStore",
    "InMemoryCredentialBackend",
    "KeyringCredentialBackend",
    "MemoryCredentialBackend",
    "PermanentRefreshError",
    "ProviderAccount",
    "ProviderAuthHandler",
    "RefreshCallback",
    "RevocationCallback",
    "TokenSet",
    "new_credential_reference",
    "redact_headers",
    "redact_mapping",
    "redact_secret",
    "redact_text",
]
