name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  code-check:
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install uv and set up Python
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: false
          python-version: "3.14"

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1

  pytest:
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install uv and set up Python
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: false
          python-version: "3.14"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes libportaudio2

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Test with pytest
        run: uv run pytest
