name: CI

on:
  pull_request:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jpetrucciani/black-check@master

  pytest:
    strategy:
        matrix:
            os: [macos-latest, ubuntu-latest]
            python-version: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install portaudio on Ubuntu
        run: sudo apt-get install -y portaudio19-dev python3-pyaudio
        if: matrix.os == "ubuntu-latest"

      - name: Install portaudio on MacOS
        run: brew install portaudio
        if: matrix.os == "macos-latest"

      - name: Install Poetry
        run: pipx install --force poetry==1.5.1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install Dependencies
        run: |
          poetry env use "${{ matrix.python-version }}"
          poetry install --no-interaction --no-cache

      - name: Fix PyTorch Poetry bug
        run: poetry add torch=2.0.0

      - name: Test with pytest
        run: poetry run pytest --dist no -n 0
